CREATE DATABASE GERU_CHALLENGE

USE GERU_CHALLENGE

----------------------CRIANDO TABELAS---------------------
CREATE TABLE SITUACAO_TAREFAS (
	ID INT IDENTITY PRIMARY KEY,
	SITUACAO VARCHAR(250) NOT NULL UNIQUE
	)

CREATE TABLE TAREFAS( 
	ID INT IDENTITY PRIMARY KEY,
	DESCRICAO VARCHAR(250) NOT NULL,
	DATA_TAREFA DATETIME NOT NULL,
	PREVISAO DATETIME NOT NULL,
	DATA_CRIACAO DATETIME NOT NULL,
	DATA_LEMBRETE DATETIME NOT NULL,
	ID_SITUACAO INT FOREIGN KEY REFERENCES SITUACAO_TAREFAS(ID)
	)

CREATE TABLE TAGS(
	ID INT IDENTITY PRIMARY KEY,
	TAG VARCHAR(230) NOT NULL UNIQUE
	)

CREATE TABLE TAREFAS_TAGS(
	ID_TAREFAS INT NOT NULL FOREIGN KEY REFERENCES TAREFAS(ID),
	ID_TAGS INT NOT NULL FOREIGN KEY REFERENCES TAGS(ID)
	)

----------------------SELECT------------------------------
--Selecionando a tabela tarefas
SELECT * FROM SITUACAO_TAREFAS
--Selecionando a tabela tarefas
SELECT * FROM TAREFAS
--Selecionando a tabela tags
SELECT * FROM TAGS
--Selecionando a tabela tags_tarefas
SELECT * FROM TAREFAS_TAGS

--Selecionando apenas as tarefas realizadas
SELECT T.DESCRICAO, T.DATA_TAREFA, T.PREVISAO, T.DATA_CRIACAO, T.DATA_LEMBRETE, T.ID_SITUACAO FROM TAREFAS T WHERE T.ID_SITUACAO = 4;

--Selecionando as tarefas pelo dia
SELECT T.DESCRICAO, T.DATA_TAREFA, T.PREVISAO, T.DATA_CRIACAO, T.DATA_LEMBRETE, T.ID_SITUACAO FROM TAREFAS T WHERE T.DATA_TAREFA = DAY(GETDATE());

--Selecionando as tarefas pela semana
SELECT T.DESCRICAO, T.DATA_TAREFA, T.PREVISAO, T.DATA_CRIACAO, T.DATA_LEMBRETE, T.ID_SITUACAO FROM TAREFAS T WHERE T.DATA_TAREFA = DATEPART ( WEEK , GETDATE());

--Selecionando as tarefas pelo mês
SELECT T.DESCRICAO, T.DATA_TAREFA, T.PREVISAO, T.DATA_CRIACAO, T.DATA_LEMBRETE, T.ID_SITUACAO FROM TAREFAS T WHERE T.DATA_TAREFA = MONTH(GETDATE());

--Selecionando as tarefas que contém as tags pelo ID
SELECT T.DESCRICAO, T.DATA_TAREFA, T.PREVISAO, T.DATA_CRIACAO, T.DATA_LEMBRETE, T.ID_SITUACAO FROM TAREFAS T LEFT JOIN TAREFAS_TAGS TG ON T.ID = TG.ID_TAREFAS; 

--Selecionando as tarefas que contém as tags pela string Tag --ESSA QUERY É REALIZADA NA API--
SELECT T.DESCRICAO, T.DATA_TAREFA, T.PREVISAO, T.DATA_CRIACAO, T.DATA_LEMBRETE, T.ID_SITUACAO FROM TAREFAS T LEFT JOIN TAGS TG ON TG.TAG = @TAG; 

----------------------INSERT------------------------------
INSERT INTO SITUACAO_TAREFAS VALUES('Agendada'), ('Em desenvolvimento'), ('Em análise'), ('Finalizada');

INSERT INTO TAREFAS VALUES('Desenvolver Api Artsign', '20/03/2019','25/03/2019',GETDATE(), '07/03/2019',1);

INSERT INTO TAGS VALUES('Back-end'), ('Front-End'), ('Referência');

INSERT INTO TAREFAS_TAGS VALUES(3, 1), (3,3)

----------------------FUNÇÕES-----------------------------

--Calculando o tempo que falta para realizar a tarefa
SELECT DATEDIFF (DAY, T.DATA_TAREFA, T.PREVISAO) AS TEMPO_RESTANTE FROM TAREFAS T 
												